name: CMake Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Configure CMake
        run: cmake -S . -B _build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage"

      - name: Build
        run: cmake --build _build

      - name: Run Tests
        run: ./_build/check

      - name: Generate Coverage Report
        run: |
          lcov --capture --directory _build --output-file coverage.info --ignore-errors mismatch
          lcov --remove coverage.info '/usr/*' '*/third-party/*' '*/tests/*' --output-file coverage.info --ignore-errors mismatch

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.info
